name: Codecov Coverage

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Usamos la v20 que es la LTS actual

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        # Usamos el comando que configuramos en el package.json
        run: npm run test:coverage 
        continue-on-error: true # Permite que Codecov suba datos aunque los tests fallen

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: gti-sos/SOS2526-17
          fail_ci_if_error: false # Para que no se ponga rojo si falla la conexión con Codecov