name: Snyk Security Scan
on: [push]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Snyk Test
        uses: snyk/actions/node@master
        continue-on-error: true  
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}