name: SOS CI Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 1. Instalamos dependencias del backend
      - name: Install backend dependencies
        run: npm install

      # 2. Instalamos y construimos el frontend
      - name: Build Frontend
        run: |
          cd src/front
          npm install
          npm run build

      # 3. Teteamos el backend con Newman
      - name: Run Newman Tests
        run: npm test