name: SOS2526-Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Backend dependencies
        run: npm install


      - name: Build Frontend (Svelte)
        run: |
          cd src/front
          npm install --no-engine-strict
          npm run build  
          
      - name: Run Newman Tests
        run: npm test
